name: Chris Anderson

# Short bio or description (displayed in the header)
description:

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/5461398?v=3&s=460

#
# Flags below are optional
#

disqus: chrisranderson

footer-links:
  github: chrisranderson
  linkedin: https://www.linkedin.com/profile/view?id=281374139&trk=nav_responsive_tab_profile_pic
  twitter: chrisdotio

google_analytics: UA-62970587-1

url: http://chrisranderson.github.io

future: true
#
# !! You don't need to change any of the configuration flags below !!
#
kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: true
            start_line: 1
# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]
# highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
